### ISSUE TITLE
need episode 8!

### ISSUE THREAD

**Issue by ghost** [machinedgod/helda#1]
great series, I love it. I would even pay for more episodes perhaps you should try Patreon. You are very good

**Comment by machinedgod** [comment]
Hey, thanks a lot, its nice to hear positive feedback! I'm getting back to it starting 2019.

**Comment by LeMikaelF** [comment]
I'm on my third time watching the whole series!

**Comment by machinedgod** [comment]
Episode 9 is up. I shall close this. Thank you for the interest.
